workflows:
  ios-build:
    name: KMP iOS Build Workflow
    max_build_duration: 60
    environment:
      kotlin: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          ./gradlew :shared:packForXcode
      - name: Build iOS Framework
        script: |
          xcodebuild -workspace ios/Dollar Wallpaper.xcworkspace \
                     -scheme <YourSchemeName> \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/Dollar Wallpaper.xcarchive \
                     archive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Dollar Wallpaper.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath $PWD/build/ios
    artifacts:
      - build/ios/*.ipa
